development:
  api:
    host: "http://news.leonardo-mbc.blue"
    #host: "http://192.168.0.50"

test:
  api:
    #host: "http://news.leonardo-mbc.blue"
    host: "http://192.168.0.50"

production:
  api:
    #host: "http://news.leonardo-mbc.blue"
    host: "http://192.168.0.50"
