development:
  api:
    ajax_host: "http://news.leonardo-mbc.blue"
    rails_host: "http://news.leonardo-mbc.blue"

test:
  api:
    ajax_host: "http://news.leonardo-mbc.blue"
    rails_host: "http://192.168.0.50"

production:
  api:
    ajax_host: "http://news.leonardo-mbc.blue"
    rails_host: "http://192.168.0.50"
