development:
  api:
    ajax_host: "http://news.leonardo-mbc.blue"
    rails_host: "http://news.leonardo-mbc.blue"

test:
  api:
    ajax_host: "http://news.leonardo-mbc.blue"
    rails_host: "Ak1ba-Edge.local/news/"

production:
  api:
    ajax_host: "http://news.leonardo-mbc.blue"
    rails_host: "Ak1ba-Edge.local/news/"
