development:
  api:
    host: "http://news.leonardo-mbc.blue"
    #host: "http://192.168.0.30"

test:
  api:
    #host: "http://news.leonardo-mbc.blue"
    host: "http://192.168.0.30"

production:
  api:
    #host: "http://news.leonardo-mbc.blue"
    host: "http://192.168.0.30"
